# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da98d83e54bcf9deb17e288aa1bf8aeb8e5999293ca942058ce1ca412767547888cb0f8dfbed043f9672b45656b38eff30cef375601bcac1b859df9d8fee4204

test:
  secret_key_base: a43d93fe2f5c538a70dc9c6f890611afc30fb85e11ba4a598b10913bdad0f550e06201342fe1c89cb44361f23efad8d38fda56198a4e4de468631c7163024b16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
